FROM ubuntu:latest AS idie-deps

WORKDIR /app

# Git & utils
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --fix-missing -y tzdata git curl ca-certificates

## Rust
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y  --default-toolchain nightly

ENV PATH="/root/.cargo/bin:${PATH}"

## Irie-lang

RUN apt-get update && apt-get install -y \
      g++ \
      gcc \
      libc6-dev \
      libffi-dev \
      libgmp-dev \
      make \
      xz-utils \
      zlib1g-dev \
      libtinfo5 \
      gnupg \
      netbase \
      haskell-stack \
  && stack upgrade --binary-only

RUN LIBTINFO_PATH=$(find / -name libtinfo.so.5) \
  && ln -s "$LIBTINFO_PATH" "$(dirname $LIBTINFO_PATH)/libtinfo.so"

RUN git clone https://github.com/emilien-jegou/Irie-lang.git /app/irie \
  && cd /app/irie \
  && make \
  && mv $(find . -type f -name 'irie-exe' | head -n1) irie # This line overwrite the symbolic link generated by the make command

FROM rust:1.55.0 AS idie-dev
RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install -y \
      wget \
      pkg-config \
      libsystemd-dev \
      libdbus-glib-1-dev \
      build-essential \
      libelf-dev \
      libseccomp-dev \
      slirp4netns \
      && rm -rf /var/lib/apt/lists/*

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY . .

RUN cargo install cargo-watch

COPY --from=idie-deps /app/irie/irie /deps/irie
