version: '3.0'

services:
  idie-test-dynamodb:
    container_name: idie-test-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    working_dir: /home/dynamodblocal
    volumes:
      - "./docker/dynamodb-test:/home/dynamodblocal/data:rw"

  idie-test-backend:
    container_name: idie-test-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://idie-test-dynamodb:8000 -timeout 30s cargo --color=always watch -q -c -w ./libs -x 'test -p idie -- --nocapture'
    tty: true
    depends_on:
      - idie-test-dynamodb
    links:
      - idie-test-dynamodb
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: eu-west-1
      AWS_DYNDB_ENDPOINT: http://idie-test-dynamodb:8000/
      CARGO_TERM_COLOR: "always"
      TERM: xterm-256color
    volumes:
      - .:/app
      - /app/target
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local
