version: '3.0'

services:
  idie-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/target
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local
